---

- name: YUM | Install acl
  yum:
    name: acl
    state: present
  when: ansible_os_family == "RedHat"

- name: APT | Install acl
  apt:
    name: acl
    state: present
  when: ansible_os_family == "Debian"

- name: STAT | Check if satis is installed
  stat:
    path: "{{ satis_installation }}"
  register: satis_installed

- name: COMPOSER | Install satis
  become_user: "{{ satis_user }}"
  composer:
    command: "create-project"
    arguments: "composer/satis --stability={{ satis_version }} --keep-vcs"
    working_dir: "{{ satis_user_home }}"
  when: satis_installed.stat.exists == false

- name: COMPOSER | Configure Composer to ignore ssl
  become_user: "{{ satis_user }}"
  composer:
    command: "config"
    arguments: "-g secure-http false"
    working_dir: "{{ satis_user_home }}"
  when: satis_composer_ignore_secure_http
  
- name: COMPOSER | Setup OAuth Tokens for polular GIT providers
  become_user: "{{ satis_user }}"
  composer:
    command: "config"
    arguments: "-g {{ item.name }} '{{ item.value }}'"
    working_dir: "{{ satis_user_home }}"
  with_items: "{{ composer_auth_tokens }}" 
  tags:
    - github_oauth
  when: composer_auth_tokens | count

- name: FILE | Fix permission on satis executable
  file:
    path: "{{ satis_bin }}"
    mode: "0755"
