---

- name: TEMPLATE | Create satis.json
  template:
    src: "satis.json.j2"
    dest: "{{ satis_config_file }}"
  register: satis_config_file_created

- name: FILE | Create build dir
  file:
    owner: "{{ satis_user }}"
    group: "{{ satis_group }}"
    path: "{{ satis_build_dir }}"
    state: directory
    mode: "0755"

- name: FIND | Count number of files in {{ satis_build_dir }}
  find:
    paths: "{{ satis_build_dir }}"
  register: find_satis_build_dir

- name: "ssh-agent hack: grant access to the {{ satis_user }} user"
  acl: 
    path: "{{ item }}" 
    etype: user
    entity: "{{ satis_user }}" 
    permissions: "rwx"
    state: present
  with_items:
    - "{{ ansible_env.SSH_AUTH_SOCK | dirname }}"
    - "{{ ansible_env.SSH_AUTH_SOCK }}"

- name: COMMAND | Build the repository
  command: "{{ satis_build_command }}"
  when: >
    satis_config_file_created.changed == true or
    find_satis_build_dir.matched == 0 or
    satis_force_build
  become: yes
  become_flags: --preserve-env=SSH_AUTH_SOCK
  become_user: "{{ satis_user }}"

- name: FILE | Fix owner/group
  file:
    path: "{{ satis_user_home }}"
    recurse: yes
    owner: "{{ satis_user }}"
    group: "{{ satis_group }}"
